version: "3"

services:
  db:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: neauthuser
      POSTGRES_PASSWORD: neauthpass
      POSTGRES_DB: neauth
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
    ports:
      - "127.0.0.1:15432:5432"
  app:
    restart: always
    build: .
    env_file: .env
    ports:
      - "4000:3000"
